name: AdminDrop
version: 1.0.1
description: Stops users from dropping items if enabled.
authors: [pyropyro78, NitroNumberOne]
main: com.pyromanticgaming.admindrop.AdminDrop
commands:
   nd:
      description: Disable/Enable item drops on death.
      usage: /<command>
      permission: AdminDrop.nd