name: AdminDrop
version: 1.0.1
description: Stops users from dropping items if enabled.
authors: [pyropyro78, NitroNumberOne]
main: com.pyromanticgaming.admindrop.AdminDrop
commands:
   ad:
      description: Disable/Enable item drops on death.
      usage: |
        /ad - Toggles on/off
        /ad [player] - Toggles other on/off
        /ad list - Lists users with Toggle on
        /ad status - Gets current status
        /ad status [player] - Gets players current status
        /ad help - Displays commands